export const ChatsActionTypes = {
  CHATS_FETCH_INIT: 'CHATS_FETCH_INIT',
  CHATS_FETCH_RESTART: 'CHATS_FETCH_RESTART',
  CHATS_FETCH_SUCCESS: 'CHATS_FETCH_SUCCESS',
  CHATS_JOIN_SUCCESS: 'CHATS_JOIN_SUCCESS',
  CHATS_CREATE_SUCCESS: 'CHATS_CREATE_SUCCESS',
  CHAT_SET_ACTIVE_CHAT: 'CHAT_SET_ACTIVE_CHAT',
  CHAT_UPDATE_USER_STATE: 'CHAT_UPDATE_USER_STATE',
  CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
  CHAT_SET_MESSAGES: 'CHAT_SET_MESSAGES',
  CHAT_REGISTER_MESSAGES_SUB: 'CHAT_REGISTER_MESSAGES_SUB',
};
